<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">

    <div class="jumbotron">
        <h1>Sobre</h1>
    </div>
    <div class="col-md-12">
        <h2>A Instituição</h2>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi eligendi repudiandae ratione, sequi necessitatibus, aliquam autem deserunt sapiente quidem consectetur amet numquam eveniet ipsam eos fugit optio accusantium vel tempore.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi eligendi repudiandae ratione, sequi necessitatibus, aliquam autem deserunt sapiente quidem consectetur amet numquam eveniet ipsam eos fugit optio accusantium vel tempore.
        </p>
        <h2>Nossas Metas</h2>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi eligendi repudiandae ratione, sequi necessitatibus, aliquam autem deserunt sapiente quidem consectetur amet numquam eveniet ipsam eos fugit optio accusantium vel tempore.
        </p>
        <h2>Valores</h2>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi eligendi repudiandae ratione, sequi necessitatibus, aliquam autem deserunt sapiente quidem consectetur amet numquam eveniet ipsam eos fugit optio accusantium vel tempore.
        </p>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>