<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">

    <div class="jumbotron">
        <h1>Entre em contacto conosco</h1>
    </div>
    <div class="col-md-12">
        <h2>Fala Conosco por meio dos contactos abaixo!</h2>

        <p>
            Telefone: <a href="tel:841234567"><strong>841234567</strong></a> <br>
            Email: <a href="mailto:email@gmail.com"> <strong>email@gmail.com</strong></a>
        </p>

        <p>
            Ou através do formulário abaixo:
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Nome</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Nome completo" name="name">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Email (Campo Obrigatório)</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Assunto</label>
                <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Assunto" name="subject">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Mensagem</label>
                <textarea name="message" id="" cols="30" rows="5" class="form-control"></textarea>
            </div>
            <button type="submit" class="btn btn-success">Enviar Contacto</button>
        </form>
        </p>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>