<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">

    <div class="jumbotron">
        <h1>Bem Vindo a Zombo Technology</h1>
        <p>This example is a quick exercise to illustrate how the default, static navbar and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>
            <a class="btn btn-lg btn-primary" href="#" role="button">Saber mais &raquo;</a>
        </p>
    </div>

</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>